language: php

php:
  - 5.5
  - 5.4

env:
  - LARAVEL_VERSION="4.0.*" TESTBENCH_VERSION="2.0.*"
  - LARAVEL_VERSION="4.1.*" TESTBENCH_VERSION="2.1.*"
  - LARAVEL_VERSION="4.2.*" TESTBENCH_VERSION="2.1.*"

before_script:
  - composer self-update
  - mysql -e 'create database translatable_test;'
  - mysql -e 'CREATE USER "homestead"@"localhost" IDENTIFIED BY "secret";'
  - composer require orchestra/testbench:"$TESTBENCH_VERSION" --dev
  - composer require illuminate/support:"$LARAVEL_VERSION" --dev
  - composer install

script: phpunit --coverage-text
